### ISSUE TITLE
Adding the Oil Extractors to the list of constructions ?

### ISSUE THREAD

**Issue by Dragomitch** [eirshy/Eirshy.DSP#1]
Hey there !
Thanks a lot for you mod, its wonderfull :D !
Sorry to open a Issue, you dont have discussions/suggestions open for your repo ^^'.

Would it be possible to do the same for the oil extractors? Something like the water Pumps would be perfect :p !

Thanks !

**Comment by eirshy** [comment]
Hey, sorry for the delay I don't really check this. I'm on the modding discord (as Eirshy), for future reference. I'll throw a readme on the root noting that.

The tick code for oil extractors makes them incapable of having more than one oil seep at once, so to do that I'd have to basically rewrite `MinerComponent.InternalUpdate` for it to even be possible. Not the worst idea to rewrite that, since glancing at it it's another thing in *desperate* need of an `Interlocked` rewrite (literally locks the planet's *entire* vein data while it works)... but that kind of thing isn't exactly in-scope for LazyOutposter.

It is however actually in-scope for ReBuffer, since that 50 internal buffer value is hard-coded. Could have RB be a soft-dep for LO and restore the Texan Fever Dream (working name) component I considered originally before cancelling it because of that rewrite issue....

Nnh. I've got a whole modding toolkit on this repo that's still in-dev I'd like to get out the door (and probably transferred into CommonAPI, since Kremnev's asked if I'd be willing) before I start picking up more rewrites. ReBuffer legit only happened to fix an issue with StaticCompression, and LazyOutposting was because I was actually playing the game some to check for more hidden issues in SC and found out PlanetaryMining was the source of all my gas giant woes.

No promises, so don't hold your breath, but it's definitely something I'll consider.

**Comment by eirshy** [comment]
Late to say it but for completeness, the rewrite issue was handled with my mod VeinityProject, and support for both global oil and advanced miners harvesting oil was also added.
