### ISSUE TITLE
[Veinity] Update 0.10.29.22010 error

### ISSUE THREAD

**Issue by PiggyWhiskey** [eirshy/Eirshy.DSP#13]
Latest update (0.10.29.22010) has broken Veinity
All miners are 'paused' not actually mining

![image](https://github.com/eirshy/Eirshy.DSP/assets/9373995/883d262f-63c5-4968-9fde-1b0256ca1e30)

**Comment by xe7485** [comment]
Same thing here.

**Comment by PiggyWhiskey** [comment]
Seems to be related to the new 'Alerts' system, the voice-over telling the player that a vein is empty

**Comment by xe7485** [comment]
This seems to fix it
`factory.NotifyVeinExhausted((int)vtarg.type, vtarg.pos );`

**Comment by eirshy** [comment]
Yeah the new alerts broke it, they added arguments to that fn. Annoying that they didn't make the vein type take in the enum, but what can you do.
I didn't look to see if I already had a ref to vein so my update needlessly grabs another, but otherwise it's fixed. Already switched it to using `vtarg` in the codebase, so whenever the next update to Veinity happens, it'll switch. Perf impact should be functionally nil anyways.

**Comment by PiggyWhiskey** [comment]
Got another error when mineral is depleted. 
![image](https://github.com/eirshy/Eirshy.DSP/assets/9373995/2268d400-0a1a-46ea-91f7-fe8f96ce60ca)

Tested with an auto-save without Veinity and no error.

**Comment by PiggyWhiskey** [comment]
^Resolved 0.2.6
