### ISSUE TITLE
Mod just turning off spliting/sorting on splitters

### ISSUE THREAD

**Issue by TroleyDEV** [eirshy/Eirshy.DSP#14]
It looks like that mod turns off sorter/priority splitting

**Comment by kaedys** [comment]
Similar issue.  Priority output seems to work as expected for me, but filters are outputs are just completely ignored, even for splitters that don't have a cargo box stuck on top.  I've had to fall back to using sorters to filter from one line to another, and avoiding mixed lines in general.

**Comment by Salvard** [comment]
Same problem here
![DSP_Bug](https://github.com/eirshy/Eirshy.DSP/assets/84709703/d8a28309-4c3f-42fa-babc-999332b36551)
Test on a game that only had this mod and on a clean save

**Comment by eirshy** [comment]
Issue was that if the filtered line was only able to invalidate itself if it wasn't the *only* valid output line in "hatless" mode. Almost all my work on this mod was with splitters under storage chests, so I never noticed.

I also fixed the mixed outputs you may have been getting from filter + chest. You'll still get mixed outputs on filter without chest, but that's because fixing it there is expensive and you probably shouldn't be using a splitter in that context anyways.
