### ISSUE TITLE
staurolite in 1.0.1 still messes ups filter

### ISSUE THREAD

**Issue by Surion79** [eirshy/Eirshy.DSP#15]
after upgrading to 1.0.1 of saurolite the fix in the changelog is not completely gone. i still see missfiltered items, although very limited. Tho BPs are based one exact splits and not 99%. it's getting clogged. Please fix

**Comment by odrai123** [comment]
+1 on this. The fix did indeed stop items from the unfiltered line spilling into the filtered line when backed up.

However the reverse issue still exists, if the filtered line backs ups it spills onto the unfiltered lines, this is not supposed to happen.

**Comment by Surion79** [comment]
@eirshy care to fix?

**Comment by eirshy** [comment]
People, seriously, read the damn readme on the repo. **I do not check here** outside of fey moods. Ping me in the discord if you need my attention.

Additionally, you should read the damn readme on Staurolite, as it pretty clearly says:
> Splitters without a storage chest on top will have mixed output on unfiltered lines.
> This is due to filtering that output being expensive, and bunnyhops being canonical means
> you should just be using those instead of having a splitter do that task.

Bunnyhops are canonical now, you should *really* redo your blueprints to not use splitters in place of bunnyhops.

If you're needing this behavior because you're trying to do sushi, then I don't really care to try to fix this without sacrificing perf, as sushi is almost impossible to not make fragile due to the lack of circuit networks.

If you're needing this behavior because you're trying to build a computer engineering project it might be possible to convince me to fix it despite the perf loss for having to actually check the *unfiltered* line, if you can explain to me your setup and why you need it.

**Comment by Surion79** [comment]
This basically breaks every published blueprint available.
Adding a storage would likely only postpone the issue.

Thanks for clearing that out in an offensive way.
This mod breaks gameplay. 
I'll advertise it accordingly.

**Comment by eirshy** [comment]
No, it really doesn't. It breaks damn near no blueprints. And not just because the "meta" was to never use splitters because they were almost unnecessary and a dreadful perf sink to the point where even a double-line of exchangers was better off using inserters on belt stubs instead of splitters.

There are only three usages of the antifilter I'm aware of:

**SUSHI**:
Putting two different resources on one belt is something you have to intentionally do, and handling it is rife with problems because you have no circuit network to ensure the quantities of each resource on the belt remain balanced to the task. Most "working" sushi setups take advantage of tech-down speeds to keep ratios roughly right, and also don't use splitters at all since splitters don't let you play with the belt speeds, which you have to do for the sushi magic to work. They also die if the line gets backed up, so having an antifilter arguably breaks potential sushi usage of the splitter. It's plausible that a Staurolite splitter, without a hat, is now actually capable of being used in a sushi setup in order to leech a line of something off of a sushi bus, like you would use a filtered inserter.
This issue is at worst neutral, at best a boon.

**BELT CROSSING**:
You **USED TO** need a double-filtering splitter was if you needed to cross belts and both lacked the space for a full up-down and didn't want to break into the tome of belt-bending. The belt placer now *automatically* performs the bunny hops you used to need the tome of belt-bending for, so **splitters in this usage are obsolete**. Even moreso because unless you use the slim splitters mod you need a massively larger footprint to use a splitter in place of a bunnyhop.
I suspect THIS is your argument for why it "breaks blueprints", as yes, it would break any belt-crossing that depends on the splitter behavior. But my argument for why I don't care is because *you do not need to use a splitter for that*. Literally just rebuild the belts, without the splitter, and it'll work. Better, actually, because cargo transit is more relatively-optimized than even my Staurolite splitters.

**BOX UNLOADING**:
There's a potential for needing a double-filtered splitter if you're doing something like two fidget spinner chests linked by inserter or that mod that lets fidget spinners have more than one item linked per chest, but Staurolite provides an antifilter when there's a chest it's pulling from due to that being functionally free comparatively.
So it's not broken in this use case.

--

The filtered line is 100% pure the resource you set. The priority rules work as they should. The only thing it doesn't do is perform an antifilter on the unfiltered line in absence of a hat. If this is necessary for some wacky computer hardware simulation project you're doing, then because game respects game I'll happily figure out something if you also explain to me the theory behind your design and why it needs this extremely *niche* feature.

But if you can't offer me a single explanation of your use case that goes into *why* you need such a niche feature, particularly one which I can't dismiss as a stupid idea in the first place, I can only assume you're whining.

Especially when this is a long-winded addition to the medium-winded response that could have been a simple "RTFM".
