### ISSUE TITLE
miner issue

### ISSUE THREAD

**Issue by Saszuke** [eirshy/Eirshy.DSP#7]
Since the newest update i can't switch between the diffrent ore types inside the miner

**Comment by eirshy** [comment]
Check your config settings, if haulers aren't enabled or if the new (as of v1.4.0) Optimizations Only mode is enabled, you won't be able to.
Otherwise I'd need way more to go on, 'cause right now it works on my machine and I've not been getting pinged in the discord by any known users with this issue.
